# 수요미식회 방문자리뷰 TOP30 #

In [70]:
from selenium import webdriver
import re

driver = webdriver.Chrome('C:/Temp/chromedriver')
driver.implicitly_wait(3) 
driver.get('https://map.naver.com/v5/search/%EC%88%98%EC%9A%94%EB%AF%B8%EC%8B%9D%ED%9A%8C') 
import time

names_list = []
reviews_list = []
review_counts = []

stopFlag = False
time.sleep(2)
driver.switch_to.frame("searchIframe")

while True :
    count = 9
    while True :
        try :
            driver.execute_script("var su = arguments[0]; var dom=document.querySelectorAll('#_pcmap_list_scroll_container>ul>li')[su]; dom.scrollIntoView();", count)
            time.sleep(2)
        except :        
            break
        count += 10
    names = driver.find_elements_by_css_selector("span._3Yilt")
    reviews = driver.find_elements_by_css_selector("#_pcmap_list_scroll_container > ul > li > div.Ow5Yt > a > div > span._3Yzhl:nth-child(2)")

    for i in names:
        names_list.append(i.text)
    for i in reviews:
        reviews_list.append(i.text)
        
    first_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    linkurl = '#app-root > div > div._2lx2y > div._2ky45 > a:nth-child(7)'
    linkNum = driver.find_element_by_css_selector(linkurl)  
    linkNum.click() 
    time.sleep(5)
    second_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    
    if first_list == second_list:
        stropFlag = True
        break
        
names_list.remove('징광문화')   # 방문자리뷰 없는 식당 제외

In [71]:
import pandas as pd

r = re.compile(".*방문자리뷰")
new_reviews_list = list(filter(r.match, reviews_list))                                   # 방문자 리뷰수 정보만 추리기 

review_counts = [re.sub(r"방문자리뷰",'', counts) for counts in new_reviews_list]       # 방문자 리뷰수 숫자값만 추리기 
review_counts = [re.sub(r"\W",'', counts) for counts in review_counts]                  # , 등 숫자가 아닌거 없애기 

for i in range(0, len(review_counts)):
    review_counts[i] = int(review_counts[i])                                             # 리스트에있는 모든 string형 자료를  integer형으로 변환하기 

df = pd.DataFrame(list(zip(names_list, review_counts)), columns = ['식당명', '리뷰수'])    # 식당명과 리뷰수를 Column으로 가지는 데이터프레임 만들기 
pd.set_option("display.max_rows", None, "display.max_columns", None)                       # display 했을때 중간에 생략되지 않고 모든 정보 보이게 하기 

sorted_df = df.sort_values(by=['리뷰수'], ascending=False)                                   # 데이터프레임 descending order로 sorting 하기 

top_df = sorted_df[:30]   

display(top_df)               # 리뷰수 상위 30개의 식당 정보만 출력 

top_df.to_csv('project_data/수요미식회.csv')

#print(len(names_list))
#print(len(review_counts))

             식당명    리뷰수
18     카페 노티드 청담  11412
227          목향원   5183
131        애플하우스   4959
221     다운타우너 한남   3080
163        서촌스코프   2991
125   엘림들깨수제비칼국수   2872
213  로리스 더 프라임 립   2630
248        명동돈가스   2628
117  기와집순두부 조안본점   2582
247     정돈 대학로본점   2466
42         서일순대국   2180
167        네거리식당   2139
79         두꺼비게장   2133
291      하동관명동본점   2005
132   쪼매매운떡볶이 공릉   1950
157         남포면옥   1788
285         깡통만두   1779
149    농민백암순대 본점   1737
278          듀자미   1737
193       진미평양냉면   1734
35        리틀넥 청담   1717
89       미가훠궈양고기   1661
37        사랑방칼국수   1657
215      피터팬1978   1625
71      소금집델리 망원   1605
48      잉글랜드왕돈까스   1520
11            계림   1429
114      수영 돼지국밥   1424
195      정인면옥 본점   1407
277          키에리   1360

# 생생정보 방문자리뷰 TOP30 #

In [72]:
from selenium import webdriver
import re

driver = webdriver.Chrome('C:/Temp/chromedriver')
driver.implicitly_wait(3) 
driver.get('https://map.naver.com/v5/search/2TV%EC%83%9D%EC%83%9D%EC%A0%95%EB%B3%B4') 
import time

names_list = []
reviews_list = []
review_counts = []

stopFlag = False
time.sleep(2)
driver.switch_to.frame("searchIframe")

while True :
    count = 9
    while True :
        try :
            driver.execute_script("var su = arguments[0]; var dom=document.querySelectorAll('#_pcmap_list_scroll_container>ul>li')[su]; dom.scrollIntoView();", count)
            time.sleep(2)
        except :        
            break
        count += 10
    names = driver.find_elements_by_css_selector("span._3Yilt")
    reviews = driver.find_elements_by_css_selector("#_pcmap_list_scroll_container > ul > li > div.Ow5Yt > a > div > span._3Yzhl:nth-child(2)")

    for i in names:
        names_list.append(i.text)
    for i in reviews:
        reviews_list.append(i.text)
        
    first_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    linkurl = '#app-root > div > div._2lx2y > div._2ky45 > a:nth-child(7)'
    linkNum = driver.find_element_by_css_selector(linkurl)  
    linkNum.click() 
    time.sleep(5)
    second_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    
    if first_list == second_list:
        stropFlag = True
        break
        
names_list.remove('용광가든') 
names_list.remove('상범이네 만두&도너츠')
names_list.remove('시장칼국수') 
names_list.remove('거금특산품')
names_list.remove('여포횟집') 
names_list.remove('싱글벙글떡볶이')
names_list.remove('할머니의 부엌')

In [73]:
import pandas as pd

r = re.compile(".*방문자리뷰")
new_reviews_list = list(filter(r.match, reviews_list))                                   # 방문자 리뷰수 정보만 추리기 

review_counts = [re.sub(r"방문자리뷰",'', counts) for counts in new_reviews_list]       # 방문자 리뷰수 숫자값만 추리기 
review_counts = [re.sub(r"\W",'', counts) for counts in review_counts]                  # , 등 숫자가 아닌거 없애기 

for i in range(0, len(review_counts)):
    review_counts[i] = int(review_counts[i])                                             # 리스트에있는 모든 string형 자료를  integer형으로 변환하기 

df = pd.DataFrame(list(zip(names_list, review_counts)), columns = ['식당명', '리뷰수'])    # 식당명과 리뷰수를 Column으로 가지는 데이터프레임 만들기 
pd.set_option("display.max_rows", None, "display.max_columns", None)                       # display 했을때 중간에 생략되지 않고 모든 정보 보이게 하기 

sorted_df = df.sort_values(by=['리뷰수'], ascending=False)                                   # 데이터프레임 descending order로 sorting 하기 

top_df = sorted_df[:30]   

display(top_df)               # 리뷰수 상위 30개의 식당 정보만 출력 

top_df.to_csv('project_data/생생정보.csv')

               식당명    리뷰수
93             이성당  25062
255     문개항아리 조천본점   6079
166           장인의집   3544
139        야자수마을카페   3535
268            다우랑   3519
275          강릉갈비찜   3495
174        원조호수삼계탕   3343
281          푸른회식당   3279
98            흔들바위   2994
97         봉평메밀미가연   2799
31           일미닭강정   2413
274          또와요짬뽕   2251
22        산골항아리바베큐   2237
273           제철쌈밥   2221
280    잘빠진메밀 서촌 본점   1863
20        최미자소머리국밥   1857
138        중앙탑메밀마당   1613
260          꾸본난로회   1611
42         파인에이플러스   1516
52          배터지는게장   1499
147           그린횟집   1382
151           대보명가   1337
92             빈해원   1304
270          교동고로케   1179
118  이서방왕족발보쌈 수원본점   1172
50       미친닭 & 취하루   1153
178            나눌터   1131
292        옹기골만찬쌈밥   1113
238       춘천산속에닭갈비   1112
120            호족반   1051

# 생방송투데이 방문자리뷰 TO30 #

In [74]:
from selenium import webdriver
import re

driver = webdriver.Chrome('C:/Temp/chromedriver')
driver.implicitly_wait(3) 
driver.get('https://map.naver.com/v5/search/%EC%83%9D%EB%B0%A9%EC%86%A1%ED%88%AC%EB%8D%B0%EC%9D%B4') 
import time

names_list = []
reviews_list = []
review_counts = []

stopFlag = False
time.sleep(2)
driver.switch_to.frame("searchIframe")

while True :
    count = 9
    while True :
        try :
            driver.execute_script("var su = arguments[0]; var dom=document.querySelectorAll('#_pcmap_list_scroll_container>ul>li')[su]; dom.scrollIntoView();", count)
            time.sleep(2)
        except :        
            break
        count += 10
    names = driver.find_elements_by_css_selector("span._3Yilt")
    reviews = driver.find_elements_by_css_selector("#_pcmap_list_scroll_container > ul > li > div.Ow5Yt > a > div > span._3Yzhl:nth-child(2)")

    for i in names:
        names_list.append(i.text)
    for i in reviews:
        reviews_list.append(i.text)
        
    first_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    linkurl = '#app-root > div > div._2lx2y > div._2ky45 > a:nth-child(7)'
    linkNum = driver.find_element_by_css_selector(linkurl)  
    linkNum.click() 
    time.sleep(5)
    second_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    
    if first_list == second_list:
        stropFlag = True
        break
        
names_list.remove('옥동횟집') 
names_list.remove('오공주왕만두')
names_list.remove('호떡남매') 
names_list.remove('천안온누리호두과자')
names_list.remove('중앙시장48호점와플') 
names_list.remove('경상도떡볶이')
names_list.remove('평창칼국수')
names_list.remove('수수부꾸미') 
names_list.remove('섬마을밥상') 
names_list.remove('코스모스분식')
names_list.remove('월화김치말이삼겹살') 
names_list.remove('바다왕국횟집') 
names_list.remove('해동회수산') 
names_list.remove('동해농원') 
names_list.remove('우도횟집') 
names_list.remove('대한치킨당 건대점') 
names_list.remove('적량횟집')

In [75]:
import pandas as pd

r = re.compile(".*방문자리뷰")
new_reviews_list = list(filter(r.match, reviews_list))                                   # 방문자 리뷰수 정보만 추리기 

review_counts = [re.sub(r"방문자리뷰",'', counts) for counts in new_reviews_list]       # 방문자 리뷰수 숫자값만 추리기 
review_counts = [re.sub(r"\W",'', counts) for counts in review_counts]                  # , 등 숫자가 아닌거 없애기 

for i in range(0, len(review_counts)):
    review_counts[i] = int(review_counts[i])                                             # 리스트에있는 모든 string형 자료를  integer형으로 변환하기 

df = pd.DataFrame(list(zip(names_list, review_counts)), columns = ['식당명', '리뷰수'])    # 식당명과 리뷰수를 Column으로 가지는 데이터프레임 만들기 
pd.set_option("display.max_rows", None, "display.max_columns", None)                       # display 했을때 중간에 생략되지 않고 모든 정보 보이게 하기 

sorted_df = df.sort_values(by=['리뷰수'], ascending=False)                                   # 데이터프레임 descending order로 sorting 하기 

top_df = sorted_df[:30]   

display(top_df)               # 리뷰수 상위 30개의 식당 정보만 출력 

top_df.to_csv('project_data/생방송투데이.csv')

                식당명   리뷰수
254           레드브릿지  6410
225     강릉 수제 어묵고로케  6401
174            글린공원  5302
211      어거스트 힐 강남점  4598
250         삼고집 파주점  4451
101        제주오성갈치조림  4392
28             칼리오페  4066
75           카페아스타나  3604
151             러블랑  3452
255         로쏘 1924  3323
117          메인스트리트  3208
18       닭사부일체 이천본점  3140
231             더포레  2987
123      제로니모 커피하우스  2750
194            막불감동  2461
235        을밀대 평양냉면  2298
135       빵공장라뜰리에김가  2055
59            오늘제빵소  1999
12              라온숨  1917
233       대한횟집 만세튀김  1851
193             신송당  1794
162            남포면옥  1788
201          이가네떡볶이  1757
157            우스블랑  1750
91              로컬릿  1702
263            헤리베르  1684
257         중앙탑메밀마당  1613
220  용호동할매팥빙수단팥죽 본점  1573
150             숲마을  1568
213           서울앵무새  1563

# 생활의달인 방문자리뷰 TOP30 #

In [82]:
from selenium import webdriver
import re

driver = webdriver.Chrome('C:/Temp/chromedriver')
driver.implicitly_wait(3) 
driver.get('https://map.naver.com/v5/search/%EC%83%9D%ED%99%9C%EC%9D%98%EB%8B%AC%EC%9D%B8') 
import time

names_list = []
reviews_list = []
review_counts = []

stopFlag = False
time.sleep(2)
driver.switch_to.frame("searchIframe")

while True :
    count = 9
    while True :
        try :
            driver.execute_script("var su = arguments[0]; var dom=document.querySelectorAll('#_pcmap_list_scroll_container>ul>li')[su]; dom.scrollIntoView();", count)
            time.sleep(2)
        except :        
            break
        count += 10
    names = driver.find_elements_by_css_selector("span._3Yilt")
    reviews = driver.find_elements_by_css_selector("#_pcmap_list_scroll_container > ul > li > div.Ow5Yt > a > div > span._3Yzhl:nth-child(2)")

    for i in names:
        names_list.append(i.text)
    for i in reviews:
        reviews_list.append(i.text)
        
    first_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    linkurl = '#app-root > div > div._2lx2y > div._2ky45 > a:nth-child(7)'
    linkNum = driver.find_element_by_css_selector(linkurl)  
    linkNum.click() 
    time.sleep(5)
    second_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    
    if first_list == second_list:
        stropFlag = True
        break
        
names_list.remove('사랑분식') 
names_list.remove('달달구리호떡')
names_list.remove('유강엄마손김밥') 
names_list.remove('서신분식')
names_list.remove('옛날수제도너츠') 
names_list.remove('천일녹즙')
names_list.remove('와글와글')
names_list.remove('보라찐빵') 
names_list.remove('엄마매점') 
names_list.remove('중동오뎅집')
names_list.remove('40년전통그시절그맛') 
names_list.remove('원조왕떡볶이분식') 
names_list.remove('우리하우스') 
names_list.remove('도너츠전문점맥스넛')

In [83]:
import pandas as pd

r = re.compile(".*방문자리뷰")
new_reviews_list = list(filter(r.match, reviews_list))                                   # 방문자 리뷰수 정보만 추리기 

review_counts = [re.sub(r"방문자리뷰",'', counts) for counts in new_reviews_list]       # 방문자 리뷰수 숫자값만 추리기 
review_counts = [re.sub(r"\W",'', counts) for counts in review_counts]                  # , 등 숫자가 아닌거 없애기 

for i in range(0, len(review_counts)):
    review_counts[i] = int(review_counts[i])                                             # 리스트에있는 모든 string형 자료를  integer형으로 변환하기 

df = pd.DataFrame(list(zip(names_list, review_counts)), columns = ['식당명', '리뷰수'])    # 식당명과 리뷰수를 Column으로 가지는 데이터프레임 만들기 
pd.set_option("display.max_rows", None, "display.max_columns", None)                       # display 했을때 중간에 생략되지 않고 모든 정보 보이게 하기 

sorted_df = df.sort_values(by=['리뷰수'], ascending=False)                                   # 데이터프레임 descending order로 sorting 하기 

top_df = sorted_df[:30]   

display(top_df)               # 리뷰수 상위 30개의 식당 정보만 출력 

top_df.to_csv('project_data/생활의달인.csv')

                 식당명   리뷰수
225   디라이프스타일키친 광화문점  5498
29          속초붉은대게수산  3929
80           로쏘 1924  3323
284             배키욘방  2668
156            다연닭갈비  2520
187              르봉뺑  2012
208             솔트24  1345
229            수원의아침  1177
93           불티나만두찐빵  1153
209  수진분식 성남중앙지하쇼핑몰점  1147
273           돌아온떡볶이  1114
193             짱떡볶이  1093
263       나블리 베이커리카페  1058
176            라 스위스  1040
66              르뺑블랑  1028
106             만두장성  1021
239            육림닭강정  1007
128               마초   974
69             홍천쌀찐빵   959
32             교암막국수   932
201           함스베이커리   923
140               르팡   894
148           하루베이커리   881
155           서두산 딤섬   846
57               삼미당   835
252            밀베이커리   823
218           역촌왕돈까스   823
91               신성당   807
211         밀한줌 베이커리   781
24           솔밭가든막국수   773

# 맛있는녀석들 방문자리뷰 TOP30

In [84]:
from selenium import webdriver
import re

driver = webdriver.Chrome('C:/Temp/chromedriver')
driver.implicitly_wait(3) 
driver.get('https://map.naver.com/v5/search/%EB%A7%9B%EC%9E%88%EB%8A%94%EB%85%80%EC%84%9D%EB%93%A4') 
import time

names_list = []
reviews_list = []
review_counts = []

stopFlag = False
time.sleep(2)
driver.switch_to.frame("searchIframe")

while True :
    count = 9
    while True :
        try :
            driver.execute_script("var su = arguments[0]; var dom=document.querySelectorAll('#_pcmap_list_scroll_container>ul>li')[su]; dom.scrollIntoView();", count)
            time.sleep(2)
        except :        
            break
        count += 10
    names = driver.find_elements_by_css_selector("span._3Yilt")
    reviews = driver.find_elements_by_css_selector("#_pcmap_list_scroll_container > ul > li > div.Ow5Yt > a > div > span._3Yzhl:nth-child(2)")

    for i in names:
        names_list.append(i.text)
    for i in reviews:
        reviews_list.append(i.text)
        
    first_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    linkurl = '#app-root > div > div._2lx2y > div._2ky45 > a:nth-child(7)'
    linkNum = driver.find_element_by_css_selector(linkurl)  
    linkNum.click() 
    time.sleep(5)
    second_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    
    if first_list == second_list:
        stropFlag = True
        break
      
names_list.remove('카페속초에살다')

In [85]:
import pandas as pd

r = re.compile(".*방문자리뷰")
new_reviews_list = list(filter(r.match, reviews_list))                                   # 방문자 리뷰수 정보만 추리기 

review_counts = [re.sub(r"방문자리뷰",'', counts) for counts in new_reviews_list]       # 방문자 리뷰수 숫자값만 추리기 
review_counts = [re.sub(r"\W",'', counts) for counts in review_counts]                  # , 등 숫자가 아닌거 없애기 

for i in range(0, len(review_counts)):
    review_counts[i] = int(review_counts[i])                                             # 리스트에있는 모든 string형 자료를  integer형으로 변환하기 

df = pd.DataFrame(list(zip(names_list, review_counts)), columns = ['식당명', '리뷰수'])    # 식당명과 리뷰수를 Column으로 가지는 데이터프레임 만들기 
pd.set_option("display.max_rows", None, "display.max_columns", None)                       # display 했을때 중간에 생략되지 않고 모든 정보 보이게 하기 

sorted_df = df.sort_values(by=['리뷰수'], ascending=False)                                   # 데이터프레임 descending order로 sorting 하기 

top_df = sorted_df[:30]   

display(top_df)               # 리뷰수 상위 30개의 식당 정보만 출력 

top_df.to_csv('project_data/맛있는녀석들.csv')

                 식당명    리뷰수
297              이성당  25062
294           성심당 본점  20407
57           명동교자 본점  11758
296          씨엘비베이커리  10504
145  강릉짬뽕순두부 동화가든 본점   8593
173        춘천통나무집닭갈비   6358
275         나정순할매쭈꾸미   6305
288           빕스 대방점   4656
226            동동국수집   4610
158         더아리엘 목동점   4388
298              대원당   4093
253         팔당초계국수본점   3966
295          맘모스베이커리   3765
276           마복림떡볶이   3734
260          뚱보할매김밥집   3317
151            태평소국밥   3317
11            메인스트리트   3208
293         궁전제과 충장점   3146
191              한일옥   2906
186            본수원갈비   2894
266          춘심이네 본점   2875
268         원조남산왕돈까스   2803
150            일호점미역   2716
152            오씨칼국수   2662
82           팀호완 삼성점   2629
10                몽탄   2586
89           청어람 망원점   2462
118              청진옥   2362
220             오뎅식당   2234
63          조조칼국수 본점   2108

 # 골목식당 방문자리뷰 TOP30 #
 
 ###  93 개  중  30 ###
 #####  linkurl = '#app-root > div > div._2lx2y > div._2ky45 > a:nth-child(4)'  로 변경   #####

In [86]:
from selenium import webdriver
import re

driver = webdriver.Chrome('C:/Temp/chromedriver')
driver.implicitly_wait(3) 
driver.get('https://map.naver.com/v5/search/%EA%B3%A8%EB%AA%A9%EC%8B%9D%EB%8B%B9') 
import time

names_list = []
reviews_list = []
review_counts = []

stopFlag = False
time.sleep(2)
driver.switch_to.frame("searchIframe")

while True :
    count = 9
    while True :
        try :
            driver.execute_script("var su = arguments[0]; var dom=document.querySelectorAll('#_pcmap_list_scroll_container>ul>li')[su]; dom.scrollIntoView();", count)
            time.sleep(2)
        except :        
            break
        count += 10
    names = driver.find_elements_by_css_selector("span._3Yilt")
    reviews = driver.find_elements_by_css_selector("#_pcmap_list_scroll_container > ul > li > div.Ow5Yt > a > div > span._3Yzhl:nth-child(2)")

    for i in names:
        names_list.append(i.text)
    for i in reviews:
        reviews_list.append(i.text)
        
    first_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    linkurl = '#app-root > div > div._2lx2y > div._2ky45 > a:nth-child(4)'
    linkNum = driver.find_element_by_css_selector(linkurl)  
    linkNum.click() 
    time.sleep(5)
    second_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    
    if first_list == second_list:
        stropFlag = True
        break
        
names_list.remove("돈돈")
names_list.remove("타코타마")
names_list.remove("미나상스테이크")

In [87]:
import pandas as pd

r = re.compile(".*방문자리뷰")
new_reviews_list = list(filter(r.match, reviews_list))                                   # 방문자 리뷰수 정보만 추리기 

review_counts = [re.sub(r"방문자리뷰",'', counts) for counts in new_reviews_list]       # 방문자 리뷰수 숫자값만 추리기 
review_counts = [re.sub(r"\W",'', counts) for counts in review_counts]                  # , 등 숫자가 아닌거 없애기 

for i in range(0, len(review_counts)):
    review_counts[i] = int(review_counts[i])                                             # 리스트에있는 모든 string형 자료를  integer형으로 변환하기 

df = pd.DataFrame(list(zip(names_list, review_counts)), columns = ['식당명', '리뷰수'])    # 식당명과 리뷰수를 Column으로 가지는 데이터프레임 만들기 
pd.set_option("display.max_rows", None, "display.max_columns", None)                       # display 했을때 중간에 생략되지 않고 모든 정보 보이게 하기 

sorted_df = df.sort_values(by=['리뷰수'], ascending=False)                                   # 데이터프레임 descending order로 sorting 하기 

top_df = sorted_df[:30]   

display(top_df)               # 리뷰수 상위 30개의 식당 정보만 출력 

top_df.to_csv('project_data/골목식당.csv')

            식당명   리뷰수
47           연돈  2884
75       오복함흥냉면  1226
36  THE 신촌's 덮죽  1032
33       스마일닭강정   889
73       여기가좋겠네   797
42         경복식당   728
66        해미우시장   727
40        군포왕족발   725
62         갓몬스터   724
32        지니 피자   710
88      필동함박 본점   707
43   기찻길풍경 야채곱창   705
19          띠아낭   669
12    미소짓는돈까's집   611
34           헬로   600
25       사가정만두만   594
76          버거인   586
60           PS   579
15   옹기종기 감자옹심이   574
80         만스김밥   568
57        부리또만나   558
11        버거스타일   558
64        추억의집밥   490
84         시장회집   460
48   맛짱할매의 멸치국수   459
52         마몽함박   448
68          쌤김밥   436
17        킹콩파스타   426
67        맛이나식당   422
70       일운충무김밥   417

# 모닝와이드 방문자리뷰 TOP30 #

In [88]:
from selenium import webdriver
import re

driver = webdriver.Chrome('C:/Temp/chromedriver')
driver.implicitly_wait(3) 
driver.get('https://map.naver.com/v5/search/%EB%AA%A8%EB%8B%9D%EC%99%80%EC%9D%B4%EB%93%9C') 
import time

names_list = []
reviews_list = []
review_counts = []

stopFlag = False
time.sleep(2)
driver.switch_to.frame("searchIframe")

while True :
    count = 9
    while True :
        try :
            driver.execute_script("var su = arguments[0]; var dom=document.querySelectorAll('#_pcmap_list_scroll_container>ul>li')[su]; dom.scrollIntoView();", count)
            time.sleep(2)
        except :        
            break
        count += 10
    names = driver.find_elements_by_css_selector("span._3Yilt")
    reviews = driver.find_elements_by_css_selector("#_pcmap_list_scroll_container > ul > li > div.Ow5Yt > a > div > span._3Yzhl:nth-child(2)")

    for i in names:
        names_list.append(i.text)
    for i in reviews:
        reviews_list.append(i.text)
        
    first_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    linkurl = '#app-root > div > div._2lx2y > div._2ky45 > a:nth-child(7)'
    linkNum = driver.find_element_by_css_selector(linkurl)  
    linkNum.click() 
    time.sleep(5)
    second_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    
    if first_list == second_list:
        stropFlag = True
        break
        
names_list.remove("카페OLTIN-VODIY")
names_list.remove("엄마손맛식당반찬")
names_list.remove("뜰방호프")
names_list.remove("용두성")
names_list.remove("강화집")

names_list.remove("청아수산")
names_list.remove("서해식당")
names_list.remove("진미식당")
names_list.remove("인천당")
names_list.remove("초원팥죽")

names_list.remove("순창전통유과")
names_list.remove("할매떡볶이")
names_list.remove("대왕칼국수")
names_list.remove("일송정검은돌장어구이")
names_list.remove("라스타 우장산역점")

names_list.remove("푸드나눔카페")
names_list.remove("순우리한우")
names_list.remove("풍차닭알탕")
names_list.remove("마돈나")
names_list.remove("기찬빌리지")

names_list.remove("힙펍")
names_list.remove("문화다방")
names_list.remove("코코팰리체")

In [89]:
import pandas as pd

r = re.compile(".*방문자리뷰")
new_reviews_list = list(filter(r.match, reviews_list))                                   # 방문자 리뷰수 정보만 추리기 

review_counts = [re.sub(r"방문자리뷰",'', counts) for counts in new_reviews_list]       # 방문자 리뷰수 숫자값만 추리기 
review_counts = [re.sub(r"\W",'', counts) for counts in review_counts]                  # , 등 숫자가 아닌거 없애기 

for i in range(0, len(review_counts)):
    review_counts[i] = int(review_counts[i])                                             # 리스트에있는 모든 string형 자료를  integer형으로 변환하기 

df = pd.DataFrame(list(zip(names_list, review_counts)), columns = ['식당명', '리뷰수'])    # 식당명과 리뷰수를 Column으로 가지는 데이터프레임 만들기 
pd.set_option("display.max_rows", None, "display.max_columns", None)                       # display 했을때 중간에 생략되지 않고 모든 정보 보이게 하기 

sorted_df = df.sort_values(by=['리뷰수'], ascending=False)                                   # 데이터프레임 descending order로 sorting 하기 

top_df = sorted_df[:30]   

display(top_df)               # 리뷰수 상위 30개의 식당 정보만 출력 

top_df.to_csv('project_data/모닝와이드.csv')

                    식당명   리뷰수
240                  연경  4357
100                보스대게  2979
193                 마이무  2543
273                진아떡집  2411
247             용성통닭 본점  2407
176                 계열사  2299
219            을밀대 평양냉면  2298
167                 오성당  2199
64            등촌 최월선칼국수  2138
113              강민주의들밥  1892
152                남포면옥  1788
213                  벌집  1745
228                경기떡집  1576
225            잉글랜드왕돈까스  1520
154                산수갑산  1510
155            정은숙초당순두부  1442
145                풍미통닭  1434
130                 회동집  1421
255               로타리식당  1381
73                  노라바  1350
256                 야바이  1346
222                은하곱창  1316
134              옛날진미국수  1279
45               국물없는우동  1224
196  한식미담길 인천공항제2여객터미널점  1193
153                 동원집  1163
177              갈비1987  1144
92                   미가  1124
212               혜화칼국수  1083
35                  복진면  1039

# 6시내고향 방문자리뷰 TOP30 #

In [90]:
from selenium import webdriver
import re

driver = webdriver.Chrome('C:/Temp/chromedriver')
driver.implicitly_wait(3) 
driver.get('https://map.naver.com/v5/search/6%EC%8B%9C%EB%82%B4%EA%B3%A0%ED%96%A5') 
import time

names_list = []
reviews_list = []
review_counts = []

stopFlag = False
time.sleep(2)
driver.switch_to.frame("searchIframe")

while True :
    count = 9
    while True :
        try :
            driver.execute_script("var su = arguments[0]; var dom=document.querySelectorAll('#_pcmap_list_scroll_container>ul>li')[su]; dom.scrollIntoView();", count)
            time.sleep(2)
        except :        
            break
        count += 10
    names = driver.find_elements_by_css_selector("span._3Yilt")
    reviews = driver.find_elements_by_css_selector("#_pcmap_list_scroll_container > ul > li > div.Ow5Yt > a > div > span._3Yzhl:nth-child(2)")

    for i in names:
        names_list.append(i.text)
    for i in reviews:
        reviews_list.append(i.text)
        
    first_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    linkurl = '#app-root > div > div._2lx2y > div._2ky45 > a:nth-child(7)'
    linkNum = driver.find_element_by_css_selector(linkurl)  
    linkNum.click() 
    time.sleep(5)
    second_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    
    if first_list == second_list:
        stropFlag = True
        break
        
names_list.remove("북카페문")
names_list.remove("암태민박식당")
names_list.remove("어성호")
names_list.remove("은혜네손칼국수")
names_list.remove("탱탱치킨")

names_list.remove("생선구이")
names_list.remove("시장횟집식당")
names_list.remove("부산어묵한오뎅")
names_list.remove("양도어판장 황금호")
names_list.remove("토닥토닥")

names_list.remove("찐땡소머리국밥")
names_list.remove("현아네만두")
names_list.remove("가수가하는맛집")
names_list.remove("대가한정식")
names_list.remove("도촌송어양어장가든")

names_list.remove("회나루")
names_list.remove("샵봉초콜릿")
names_list.remove("송아꿀빵")
names_list.remove("이가네떡볶이")
names_list.remove("보련골연꽃가든")

names_list.remove("거림계곡토종숯불닭갈비")
names_list.remove("한진수산")
names_list.remove("꿈떡제과")
names_list.remove("염창사철탕")
names_list.remove("서정횟집")

names_list.remove("우리맛집")
names_list.remove("현금식당")
names_list.remove("시민식당")
names_list.remove("마산기사식당")
names_list.remove("미아분식")

names_list.remove("더가득한감성포차")
names_list.remove("다시오마분정식")
names_list.remove("해림호횟집")
names_list.remove("카페 공앤유")
names_list.remove("장미네cafe")

names_list.remove("전통시장보신알")
names_list.remove("산해횟집초밥")
names_list.remove("신선횟집")
names_list.remove("은행나무보리밥")

In [91]:
import pandas as pd

r = re.compile(".*방문자리뷰")
new_reviews_list = list(filter(r.match, reviews_list))                                   # 방문자 리뷰수 정보만 추리기 

review_counts = [re.sub(r"방문자리뷰",'', counts) for counts in new_reviews_list]       # 방문자 리뷰수 숫자값만 추리기 
review_counts = [re.sub(r"\W",'', counts) for counts in review_counts]                  # , 등 숫자가 아닌거 없애기 

for i in range(0, len(review_counts)):
    review_counts[i] = int(review_counts[i])                                             # 리스트에있는 모든 string형 자료를  integer형으로 변환하기 

df = pd.DataFrame(list(zip(names_list, review_counts)), columns = ['식당명', '리뷰수'])    # 식당명과 리뷰수를 Column으로 가지는 데이터프레임 만들기 
pd.set_option("display.max_rows", None, "display.max_columns", None)                       # display 했을때 중간에 생략되지 않고 모든 정보 보이게 하기 

sorted_df = df.sort_values(by=['리뷰수'], ascending=False)                                   # 데이터프레임 descending order로 sorting 하기 

top_df = sorted_df[:30]   

display(top_df)               # 리뷰수 상위 30개의 식당 정보만 출력 

top_df.to_csv('project_data/6시내고향.csv')

                 식당명   리뷰수
53       슬지네찐빵 슬지제빵소  2861
59            메밀꽃필무렵  2703
114        원조 유박사 곱창  1954
188            새만금횟집  1917
256              바로방  1834
40   할머니학화호두과자 터미널본점  1529
86             대선칼국수  1172
194             솔밭묵집  1150
133             서문우동  1127
212             화랑식당  1022
258        명가충무김밥 본점  1014
97              제일식당   904
26             미진돌곱창   809
169            어부신광호   737
64              북일곰탕   732
179             삼포가든   705
178             농부밥상   652
95             포항할매집   644
218              대박집   601
234            내포해물촌   553
99              오가네빵   537
173  충무로쭈꾸미불고기 충무로본점   518
110               돌담   492
50               신식당   490
23         푸른동산 한우마을   460
236            평화떡공방   448
257            이순신꿀빵   437
141            내대막국수   435
226           평대성게국수   435
2              황금떡볶이   431

# 전지적참견시점 방문자리뷰 TOP30 #
##### '#app-root > div > div._2lx2y > div._2ky45 > a:nth-child(5)' 로 수정  #####

In [92]:
from selenium import webdriver
import re

driver = webdriver.Chrome('C:/Temp/chromedriver')
driver.implicitly_wait(3) 
driver.get('https://map.naver.com/v5/search/%EC%A0%84%EC%A7%80%EC%A0%81%EC%B0%B8%EA%B2%AC%EC%8B%9C%EC%A0%90') 
import time

names_list = []
reviews_list = []
review_counts = []

stopFlag = False
time.sleep(2)
driver.switch_to.frame("searchIframe")

while True :
    count = 9
    while True :
        try :
            driver.execute_script("var su = arguments[0]; var dom=document.querySelectorAll('#_pcmap_list_scroll_container>ul>li')[su]; dom.scrollIntoView();", count)
            time.sleep(2)
        except :        
            break
        count += 10
    names = driver.find_elements_by_css_selector("span._3Yilt")
    reviews = driver.find_elements_by_css_selector("#_pcmap_list_scroll_container > ul > li > div.Ow5Yt > a > div > span._3Yzhl:nth-child(2)")

    for i in names:
        names_list.append(i.text)
    for i in reviews:
        reviews_list.append(i.text)
        
    first_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    linkurl = '#app-root > div > div._2lx2y > div._2ky45 > a:nth-child(5)'
    linkNum = driver.find_element_by_css_selector(linkurl)  
    linkNum.click() 
    time.sleep(5)
    second_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    
    if first_list == second_list:
        stropFlag = True
        break
        
names_list.remove("금이네집")
names_list.remove("새밭식당")
names_list.remove("김삿갓초장집")

In [93]:
import pandas as pd

r = re.compile(".*방문자리뷰")
new_reviews_list = list(filter(r.match, reviews_list))                                   # 방문자 리뷰수 정보만 추리기 

review_counts = [re.sub(r"방문자리뷰",'', counts) for counts in new_reviews_list]       # 방문자 리뷰수 숫자값만 추리기 
review_counts = [re.sub(r"\W",'', counts) for counts in review_counts]                  # , 등 숫자가 아닌거 없애기 

for i in range(0, len(review_counts)):
    review_counts[i] = int(review_counts[i])                                             # 리스트에있는 모든 string형 자료를  integer형으로 변환하기 

df = pd.DataFrame(list(zip(names_list, review_counts)), columns = ['식당명', '리뷰수'])    # 식당명과 리뷰수를 Column으로 가지는 데이터프레임 만들기 
pd.set_option("display.max_rows", None, "display.max_columns", None)                       # display 했을때 중간에 생략되지 않고 모든 정보 보이게 하기 

sorted_df = df.sort_values(by=['리뷰수'], ascending=False)                                   # 데이터프레임 descending order로 sorting 하기 

                                                            
top_df = sorted_df[:30]   

display(top_df)               # 리뷰수 상위 30개의 식당 정보만 출력 

top_df.to_csv('project_data/전지적참견시점.csv')

               식당명    리뷰수
118         성심당 본점  20407
122    안성휴게소(부산방향)  19036
19         명동교자 본점  11758
121          망향휴게소   9606
119    금강휴게소(부산방향)   7261
123  서울만남의광장(부산방향)   6421
104            카페산   6242
60        하우스 베이커리   4677
100      한입소반 숙대본점   4205
11        쉐이크쉑 청담점   4194
66           제스티살룬   3326
15         일심본가콩요리   2863
49        원조남산왕돈까스   2803
53           중앙떡볶이   2592
48              몽탄   2586
47           광릉불고기   2247
126     돈까스잔치 동빙고점   2171
20         하동관명동본점   2005
85          유림 강서점   1910
68            헤이메르   1881
13      망원동즉석우동 본점   1828
107       원조순희네빈대떡   1827
35              벌집   1745
26          진미평양냉면   1734
81           온천칼국수   1554
40            맘마미아   1534
98            산골농원   1509
83         남문통닭 본점   1471
10         한남동한방통닭   1418
65        카페 차 성수점   1329

# 생방송오늘저녁 방문자리뷰 TOP30 #

In [94]:
from selenium import webdriver
import re

driver = webdriver.Chrome('C:/Temp/chromedriver')
driver.implicitly_wait(3) 
driver.get('https://map.naver.com/v5/search/%EC%83%9D%EB%B0%A9%EC%86%A1%EC%98%A4%EB%8A%98%EC%A0%80%EB%85%81') 
import time

names_list = []
reviews_list = []
review_counts = []

stopFlag = False
time.sleep(2)
driver.switch_to.frame("searchIframe")

while True :
    count = 9
    while True :
        try :
            driver.execute_script("var su = arguments[0]; var dom=document.querySelectorAll('#_pcmap_list_scroll_container>ul>li')[su]; dom.scrollIntoView();", count)
            time.sleep(2)
        except :        
            break
        count += 10
    names = driver.find_elements_by_css_selector("span._3Yilt")
    reviews = driver.find_elements_by_css_selector("#_pcmap_list_scroll_container > ul > li > div.Ow5Yt > a > div > span._3Yzhl:nth-child(2)")

    for i in names:
        names_list.append(i.text)
    for i in reviews:
        reviews_list.append(i.text)
        
    first_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    linkurl = '#app-root > div > div._2lx2y > div._2ky45 > a:nth-child(7)'
    linkNum = driver.find_element_by_css_selector(linkurl)  
    linkNum.click() 
    time.sleep(5)
    second_list = driver.find_element_by_css_selector("#_pcmap_list_scroll_container > ul > li:nth-child(1) > div.Ow5Yt > a:nth-child(1) > div._1z7ih > div > span")
    
    if first_list == second_list:
        stropFlag = True
        break
        
names_list.remove("독립문영천시장 옛날꽈배기")
names_list.remove("자연을담은식당")
names_list.remove("전주비빔밥")
names_list.remove("해뜨는식당")

names_list.remove("맛나분식")
names_list.remove("불난집식당")
names_list.remove("나룸")
names_list.remove("늘푸른청정미나리농원")
names_list.remove("평창칼국수")

In [95]:
import pandas as pd

r = re.compile(".*방문자리뷰")
new_reviews_list = list(filter(r.match, reviews_list))                                   # 방문자 리뷰수 정보만 추리기 

review_counts = [re.sub(r"방문자리뷰",'', counts) for counts in new_reviews_list]       # 방문자 리뷰수 숫자값만 추리기 
review_counts = [re.sub(r"\W",'', counts) for counts in review_counts]                  # , 등 숫자가 아닌거 없애기 

for i in range(0, len(review_counts)):
    review_counts[i] = int(review_counts[i])                                             # 리스트에있는 모든 string형 자료를  integer형으로 변환하기 

df = pd.DataFrame(list(zip(names_list, review_counts)), columns = ['식당명', '리뷰수'])    # 식당명과 리뷰수를 Column으로 가지는 데이터프레임 만들기 
pd.set_option("display.max_rows", None, "display.max_columns", None)                       # display 했을때 중간에 생략되지 않고 모든 정보 보이게 하기 

sorted_df = df.sort_values(by=['리뷰수'], ascending=False)                                   # 데이터프레임 descending order로 sorting 하기 
                                                   
top_df = sorted_df[:30]   

display(top_df)               # 리뷰수 상위 30개의 식당 정보만 출력 

top_df.to_csv('project_data/생방송오늘저녁.csv')

                    식당명   리뷰수
218                 목향원  5183
290                이진상회  4188
95                백세삼계탕  4063
84               북한산제빵소  3759
283            베이커리 밤마을  2954
176                 수아당  2940
12           엘림들깨수제비칼국수  2872
256                 계열사  2299
165                 옹근달  2271
258               가람돌솥밥  2235
151              중앙갈치식당  1905
279             시간을 들이다  1826
70               유포리막국수  1620
268                포레스트  1577
140                 청수당  1484
226        남보완해물칼국수 울산점  1412
242  코트야드 메리어트 남대문 모모카페  1384
57                  송정집  1384
184               가나안국수  1371
193                솔트24  1345
1                   한국집  1325
139                익선잡방  1254
20                하니칼국수  1241
286           진주냉면산홍 본점  1224
207                  무탄  1210
243              릴리베이커리  1189
105        순천미향 제주산방산본점  1167
103          순금이떡볶이아차산점  1160
69                태조감자국  1147
156               두둑한한판  1121